version: "2"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/khmm12/mdns-health-checker

linters:
  default: standard
  enable:
    - embeddedstructfieldcheck
    - bodyclose
    - copyloopvar
    - cyclop
    - errname
    - errorlint
    - exhaustive
    - funcorder
    - gocritic
    - gosec
    - nolintlint
    - revive
  exclusions:
    warn-unused: true
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
      # Such cases aren't reported by default.
      # Default: false
      check-type-assertions: true
    embeddedstructfieldcheck:
      # Checks that sync.Mutex and sync.RWMutex are not used as embedded fields.
      # Default: false
      forbid-mutex: true
    exhaustive:
      # Program elements to check for exhaustiveness.
      # Default: [ switch ]
      check: ["switch", "map"]
    funcorder:
      # Checks if the exported methods of a structure are placed before the non-exported ones.
      # Default: true
      struct-method: false
    nolintlint:
      # Enable to require an explanation of nonzero length after each nolint directive.
      # Default: false
      require-explanation: true
      # Enable to require nolint directives to mention the specific linter being suppressed.
      # Default: false
      require-specific: true
