# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mdns-health-checker
    main: ./cmd/mdns-health-checker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mipsle
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .Binary }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^refactor:"

release: {}
