// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"
	"time"

	"github.com/khmm12/mdns-health-checker/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMDNSProbe creates a new instance of MockMDNSProbe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMDNSProbe(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMDNSProbe {
	mock := &MockMDNSProbe{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMDNSProbe is an autogenerated mock type for the MDNSProbe type
type MockMDNSProbe struct {
	mock.Mock
}

type MockMDNSProbe_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMDNSProbe) EXPECT() *MockMDNSProbe_Expecter {
	return &MockMDNSProbe_Expecter{mock: &_m.Mock}
}

// Probe provides a mock function for the type MockMDNSProbe
func (_mock *MockMDNSProbe) Probe(ctx context.Context, host string, timeout time.Duration) (ports.HostState, error) {
	ret := _mock.Called(ctx, host, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 ports.HostState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (ports.HostState, error)); ok {
		return returnFunc(ctx, host, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) ports.HostState); ok {
		r0 = returnFunc(ctx, host, timeout)
	} else {
		r0 = ret.Get(0).(ports.HostState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, host, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMDNSProbe_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type MockMDNSProbe_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - ctx context.Context
//   - host string
//   - timeout time.Duration
func (_e *MockMDNSProbe_Expecter) Probe(ctx interface{}, host interface{}, timeout interface{}) *MockMDNSProbe_Probe_Call {
	return &MockMDNSProbe_Probe_Call{Call: _e.mock.On("Probe", ctx, host, timeout)}
}

func (_c *MockMDNSProbe_Probe_Call) Run(run func(ctx context.Context, host string, timeout time.Duration)) *MockMDNSProbe_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMDNSProbe_Probe_Call) Return(hostState ports.HostState, err error) *MockMDNSProbe_Probe_Call {
	_c.Call.Return(hostState, err)
	return _c
}

func (_c *MockMDNSProbe_Probe_Call) RunAndReturn(run func(ctx context.Context, host string, timeout time.Duration) (ports.HostState, error)) *MockMDNSProbe_Probe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMDNSStatePublisher creates a new instance of MockMDNSStatePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMDNSStatePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMDNSStatePublisher {
	mock := &MockMDNSStatePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMDNSStatePublisher is an autogenerated mock type for the MDNSStatePublisher type
type MockMDNSStatePublisher struct {
	mock.Mock
}

type MockMDNSStatePublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMDNSStatePublisher) EXPECT() *MockMDNSStatePublisher_Expecter {
	return &MockMDNSStatePublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockMDNSStatePublisher
func (_mock *MockMDNSStatePublisher) Publish(ctx context.Context, up []string, down []string) error {
	ret := _mock.Called(ctx, up, down)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, []string) error); ok {
		r0 = returnFunc(ctx, up, down)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMDNSStatePublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMDNSStatePublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - up []string
//   - down []string
func (_e *MockMDNSStatePublisher_Expecter) Publish(ctx interface{}, up interface{}, down interface{}) *MockMDNSStatePublisher_Publish_Call {
	return &MockMDNSStatePublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, up, down)}
}

func (_c *MockMDNSStatePublisher_Publish_Call) Run(run func(ctx context.Context, up []string, down []string)) *MockMDNSStatePublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMDNSStatePublisher_Publish_Call) Return(err error) *MockMDNSStatePublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMDNSStatePublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, up []string, down []string) error) *MockMDNSStatePublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
